### ISSUE TITLE
Crash on helpedit

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#423]
```
Fri Jul 19 15:15:26 :: SYSLOG: [10000] Lucien wrote new helpfile '(null)'.
Jul 19 15:15:26 :: Query to restore original helpfile:
INSERT INTO help_topic (name, body) VALUES ('SKILLS \"SKILL LEVELS\"', 'This shows you what skills you have, and to what level you have trained them.
This table will show you the numerical value for each skill level\'s name.

Skill Level Name		Numerical Value
------------------------------------------------
awful  					1
sloppy  				2
average  				3
above average  				4
good  					5
very good  				6
distinguished  				7
excellent  				8
superb  				9
learned  				10
amazing  				11-20

^WSee Also: KARMA, ATTRIBUTES^n
') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `body` = VALUES(`body`);


Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62		VPCMPEQ (%rdi), %ymm0, %ymm1
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x00000000004fded9 in generate_sql_for_helpfile (name=0x0, body=0xcd25e0 "\r\nThis shows you what skills you have, and to what level you have trained them.\r\nThis table will show you the numerical value for each skill level's name.\r\n\r\nSkill Level Name    Numerical Value\r\n-----"...) at helpedit.cpp:259
#2  0x00000000004fdc6a in helpedit_parse_main_menu (d=0xcb74a0, arg=0x7fffffffd990 "q") at helpedit.cpp:187
#3  0x00000000004fe00d in helpedit_parse (d=0xcb74a0, arg=0x7fffffffd990 "q") at helpedit.cpp:213
#4  0x00000000005d1f05 in nanny (d=0xcb74a0, arg=0x7fffffffd990 "q") at interpreter.cpp:2251
#5  0x000000000059414a in game_loop (mother_desc=3) at comm.cpp:680
#6  0x000000000059236f in init_game (port=4000) at comm.cpp:371
#7  0x00000000005922be in main (argc=1, argv=0x7fffffffe4c8) at comm.cpp:243
```

**Comment by luciensadi** [comment]
Fixed this issue; it was caused by a NULL title being passed under certain circumstances.
