### ISSUE TITLE
Memory crash on IDEA command

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#424]
```
malloc(): memory corruption

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	}
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5f80801 in __GI_abort () at abort.c:79
#2  0x00007ffff5fc9897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff60f6b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff5fd090a in malloc_printerr (str=str@entry=0x7ffff60f4e0e "malloc(): memory corruption") at malloc.c:5350
#4  0x00007ffff5fd4994 in _int_malloc (av=av@entry=0x7ffff632bc40 <main_arena>, bytes=bytes@entry=4096) at malloc.c:3738
#5  0x00007ffff5fd70fc in __GI___libc_malloc (bytes=4096) at malloc.c:3057
#6  0x00007ffff5fbe18c in __GI__IO_file_doallocate (fp=0x9d8190) at filedoalloc.c:101
#7  0x00007ffff5fce379 in __GI__IO_doallocbuf (fp=fp@entry=0x9d8190) at genops.c:365
#8  0x00007ffff5fcd498 in _IO_new_file_overflow (f=0x9d8190, ch=-1) at fileops.c:759
#9  0x00007ffff5fcb9ed in _IO_new_file_xsputn (f=0x9d8190, data=<optimized out>, n=6) at fileops.c:1266
#10 0x00007ffff5f9bb29 in _IO_vfprintf_internal (s=0x9d8190, format=0x63ad8d "%-8s (%6.6s) [%5ld] %s\n", ap=ap@entry=0x7fffffffd530) at vfprintf.c:1643
#11 0x00007ffff5fa4e54 in __fprintf (stream=<optimized out>, format=<optimized out>) at fprintf.c:32
#12 0x000000000048d439 in do_gen_write (ch=0xca8ec0, argument=0x7fffffffd9b5 "consider changing probe to output a table of values, this makes it quicker to read (if less natural) and allows direct comparison like 'probe item1 item2 item3' (they all show up in the table if they'"..., cmd=148, subcmd=2) at act.other.cpp:850
#13 0x00000000005cf5f4 in command_interpreter (ch=0xca8ec0, argument=0x7fffffffd9b0 "idea consider changing probe to output a table of values, this makes it quicker to read (if less natural) and allows direct comparison like 'probe item1 item2 item3' (they all show up in the table if "..., tcname=0xcae000 "Lucien") at interpreter.cpp:1493
#14 0x0000000000594355 in game_loop (mother_desc=3) at comm.cpp:688
#15 0x00000000005923ff in init_game (port=4000) at comm.cpp:371
#16 0x000000000059234e in main (argc=3, argv=0x7fffffffe4e8) at comm.cpp:243
```

**Comment by luciensadi** [comment]
Cannot reproduce, but this may have been caused by the newbie channel memory leak bug. Will close for now.
