### ISSUE TITLE
Crash on character quit due to null node in list

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#481]
Somewhere along the line, character possession lists are getting corrupted, which is causing crashes.

```
Fri Nov 13 14:10:06 :: CHEATLOG: [10013] (Velan) Velan wizloaded object #35526 (an orange and white capsule).
Fri Nov 13 14:11:09 :: CHEATLOG: [60517] (Velan) Velan wizloaded object #475 (a fingertip compartment).
Fri Nov 13 14:11:32 :: HELPLOG: [60517] (Velan) Failed helpfile search: cyberdoc.
Fri Nov 13 14:11:35 :: SYSLOG: [60517] (Velan) ERROR: i == object in obj_to_char(). How we even got here, I don't know.
Fri Nov 13 14:11:35 :: SYSLOG: ERROR: obj_from_char() called on obj that had no carried_by!
Fri Nov 13 14:12:04 :: WIZITEMLOG: [60610] (Velan) Velan junks: (obj 104) a platinum credstick [wizloaded], containing 2000000 nuyen
Fri Nov 13 14:13:54 :: PURGELOG: [60610] (Velan) Velan has purged (obj -1) ^rthe corpse of Doc Tanaki^n.
Fri Nov 13 14:14:04 :: CHEATLOG: [60517] (Velan) Velan junks: (obj 2041) a map of Seattle
Fri Nov 13 14:14:06 :: SYSLOG: ERROR: obj_from_char() called on obj that had no carried_by!
Fri Nov 13 14:14:25 :: CHEATLOG: [60517] (Velan) Velan wizloaded object #127 (a blank empty magazine).
Fri Nov 13 14:14:26 :: SYSLOG: [60517] (Velan) ERROR: i == object in obj_to_char(). How we even got here, I don't know.
Fri Nov 13 14:14:48 :: SYSLOG: ERROR: obj_from_char() called on obj that had no carried_by!
Fri Nov 13 14:14:54 :: CHEATLOG: [60517] (Velan) Velan wizloaded object #127 (a blank empty magazine).
Fri Nov 13 14:15:10 :: WIZITEMLOG: [60517] (Velan) Velan junks: (obj 127) a blank empty magazine [wizloaded] [restring: a 15-round heavy pistol magazine]
Fri Nov 13 14:15:20 :: CHEATLOG: [60517] (Velan) Velan wizloaded object #10005 (a gunmetal-grey Dominator).
Fri Nov 13 14:15:30 :: SYSLOG: [60517] (Velan) ERROR: i == object in obj_to_char(). How we even got here, I don't know.
Fri Nov 13 14:15:31 :: SYSLOG: ERROR: obj_from_char() called on obj that had no carried_by!
Fri Nov 13 14:15:31 :: CHEATLOG: [60517] (Velan) Velan junks: (obj 668) an Ares Predator, containing: [ (obj 127) a blank empty magazine [wizloaded] [restring: a 15-round heavy pistol magazine] ]
Nov 13 14:15:35 :: MYSQLERROR: Out of range value for column 'Vnum' at row 1
Nov 13 14:15:35 :: Offending query: INSERT INTO pfiles_inv (idnum, Vnum, Cost, Restring, Photo, Value0, Value1, Value2, Value3, Value4, Value5, Value6,Value7, Value8, Value9, Value10, Value11, Inside, Timer, ExtraFlags, Attempt, Cond, posi) VALUES (131, -1, 0, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '0', 0, 0, 2);
Fri Nov 13 14:19:09 :: SYSLOG: [35543] SYSERR: process_has_ammo received null value. Returning TRUE.
Fri Nov 13 14:19:36 :: SYSLOG: ERROR: obj_from_char() called on obj that had no carried_by!
Fri Nov 13 14:19:36 :: CHEATLOG: [35543] (Velan) Velan junks: (obj -1) ^rthe corpse of A road-raging ganger^n
Fri Nov 13 14:20:12 :: CHEATLOG: [70311] (Velan) Velan gets from (-1) ^rthe corpse of an unassuming gardener^n [restring: none]: (obj 70301) a pair of garden shears
Fri Nov 13 14:20:12 :: CHEATLOG: [70311] (Velan) Velan gets from (-1) ^rthe corpse of an unassuming gardener^n [restring: none]: (obj 70300) a blue plastic keycard embossed with ^W[^CTSS-LC^W]^n
Fri Nov 13 14:20:19 :: CHEATLOG: [70311] (Velan) Velan junks: (obj 70301) a pair of garden shears
Fri Nov 13 14:20:26 :: CHEATLOG: [70311] (Velan) Velan junks: (obj 70300) a blue plastic keycard embossed with ^W[^CTSS-LC^W]^n
Fri Nov 13 14:20:26 :: SYSLOG: ERROR: obj_from_char() called on obj that had no carried_by!
Fri Nov 13 14:20:26 :: SYSLOG: ERROR: obj_from_char() called on obj that had no carried_by!
awake: ./list.h:184: bool listClass<obj_data *>::RemoveItem(nodeStruct<T> *) [T = obj_data *]: Assertion `node != NULL' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5f96921 in __GI_abort () at abort.c:79
#2  0x00007ffff5f8648a in __assert_fail_base (fmt=0x7ffff610d750 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x64446f "node != NULL", file=file@entry=0x64447c "./list.h", line=line@entry=184, function=function@entry=0x644485 "bool listClass<obj_data *>::RemoveItem(nodeStruct<T> *) [T = obj_data *]") at assert.c:92
#3  0x00007ffff5f86502 in __GI___assert_fail (assertion=0x64446f "node != NULL", file=0x64447c "./list.h", line=184, function=0x644485 "bool listClass<obj_data *>::RemoveItem(nodeStruct<T> *) [T = obj_data *]") at assert.c:101
#4  0x000000000042bdd0 in listClass<obj_data*>::RemoveItem (this=0x9de3b0 <ObjList>, node=0x0) at ./list.h:184
#5  0x000000000042bd16 in List<obj_data*>::Remove (this=0x9de3b0 <ObjList>, item=0xde2280) at ./list.h:277
#6  0x00000000004270b5 in extract_obj (obj=0xde2280) at handler.cpp:2105
#7  0x0000000000427c97 in extract_char (ch=0xddeaa0) at handler.cpp:2168
#8  0x000000000048d68b in impl_do_quit_ (ch=0xddeaa0, argument=0x7fffffffd3b4 "", cmd=242, subcmd=1) at act.other.cpp:149
#9  0x000000000048cdb0 in do_quit (ch=0xddeaa0, argument=0x7fffffffd3b4 "", cmd=242, subcmd=1) at act.other.cpp:62
#10 0x00000000005ec336 in command_interpreter (ch=0xddeaa0, argument=0x7fffffffd3b0 "quit", tcname=0xde3be0 "Velan") at interpreter.cpp:1499
#11 0x00000000005adb04 in game_loop (mother_desc=3) at comm.cpp:751
#12 0x00000000005ab86f in init_game (port=4000) at comm.cpp:378
#13 0x00000000005ab7be in main (argc=3, argv=0x7fffffffdee8) at comm.cpp:250
A debugging session is active.

	Inferior 1 [process 23692] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]
```

**Comment by luciensadi** [comment]
This is POTENTIALLY fixed.

**Comment by AwakeMUD** [comment]
Tentatively solved with apartment code rewrite.
