### ISSUE TITLE
Carried_by not clearing properly for objects

### ISSUE THREAD

**Issue by luciensadi** [luciensadi/AwakeMUD#522]
```
(gdb) bt
#0  0x0000000000669ae2 in affect_total (ch=0x25b09d0) at handler.cpp:481
#1  0x0000000000499739 in objList::UpdateObjs (this=0xa6dcf0 <ObjList>, proto=0x2add1c0, rnum=7682) at dblist.cpp:138
#2  0x00000000004cb4e1 in iedit_parse (d=0x2ad2f10, arg=0x686e0c "y") at iedit.cpp:1390
#3  0x00000000004cc6af in iedit_parse (d=0x2ad2f10, arg=0x7fffffffd380 "q") at iedit.cpp:1576
#4  0x00000000005fc64c in nanny (d=0x2ad2f10, arg=0x7fffffffd380 "q") at interpreter.cpp:2343
#5  0x00000000005a5749 in game_loop (mother_desc=3) at comm.cpp:774
#6  0x00000000005a341f in init_game (port=4001) at comm.cpp:409
#7  0x00000000005a336e in main (argc=2, argv=0x7fffffffdeb8) at comm.cpp:253
(gdb) print *ch
$3 = {nr = 389, in_room = 0x0, was_in_room = 0x0, player = {char_name = 0x0,
    passwd = "\000\000\000\000\002\000\000\000\003\000\000\000\000\000\000\000\003\000\000\000\377\377\377\377\001\000\000\000", '\377' <repeats 12 times>, "\000\000\000\000\000\000\000\000\005\000\000\000\001 ", '\000' <repeats 15 times>, "\200@", '\000' <repeats 16 times>, "@\350\003\000\000\002", '\000' <repeats 19 times>, "\b\b\b\000\004\000\000\000\000\000\200?\000\000\000\000\003", physical_text = {keywords = 0x0, name = 0x0, room_desc = 0x0, look_desc = 0x0}, astral_text = {keywords = 0x0,
      name = 0x1743420 "monosword ares monofilament sword", room_desc = 0x1742cd0 "an Ares monosword", look_desc = 0x1742ac0 "A monofilament sword has been left here."},
    matrix_text = {
      keywords = 0x173a280 "A street samurai's choice of weapon for up-close-and-lethal confrontations.\r\nThe Ares monosword enjoys a high profile among swordsmen for its lighter\r\nweight and easier balance, and its rugged dependa"..., name = 0x0, room_desc = 0x0, look_desc = 0x0}, background = 0x0, title = 0x0, pretitle = 0x2ad0e40 "\234\002",
    whotitle = 0x0, prompt = 0x0, matrixprompt = 0x0, poofin = 0x0, poofout = 0x2ad29e0 "\r\027", highlight_color_code = 0x0, email = 0x0, multiplier = 33, sex = 0 '\000',
    level = 0 '\000', last_room = 31283856, time = {birth = 39521136, logon = 39521584, lastdisc = 33, played = 44902528}, weight = 64224, height = 681, race = 0 '\000',
    tradition = 0 '\000', aspect = 0 '\000', host = 0x25b0b70 "@+\255\002"}, real_abils = {attributes = "!\000\000\000\000\000", mag = 11072, bod_index = 685, ess = 0,
    esshole = 0, highestindex = 2896, astral_pool = 603, combat_pool = 0, hacking_pool = 0, hacking_pool_max = 2864, hacking_pool_remaining = 603, magic_pool = 0,
    casting_pool = 0, drain_pool = 353, spell_defense_pool = 0, reflection_pool = 0, offense_pool = 0, defense_pool = 1157, body_pool = 0, control_pool = 0, task_pool = {0, 0, 0,
      0, 0, 0, 0}}, aff_abils = {attributes = "\000\000\000\000\000\000", mag = 0, bod_index = 0, ess = 10, esshole = 0, highestindex = 10, astral_pool = 0, combat_pool = 5,
    hacking_pool = 0, hacking_pool_max = 0, hacking_pool_remaining = 0, magic_pool = 0, casting_pool = 0, drain_pool = 0, spell_defense_pool = 0, reflection_pool = 0,
    offense_pool = 0, defense_pool = 0, body_pool = 0, control_pool = 0, task_pool = {0, 0, 0, 0, 0, 0, 0}}, points = {mental = 17, max_mental = 0, physical = 16385,
    max_physical = 0, ballistic = {0, 0}, impact = {0, 0}, nuyen = 0, bank = 0, karma = 0, rep = 1065353216, noto = 15, tke = 0, sig = 0, init_dice = 0 '\000', init_roll = 0,
    grade = 0, extrapp = 0 '\000', sustained = "\000", extra = 0, magic_loss = 5 '\005', ess_loss = 3 '\003', domain = 3 '\003', resistpain = 0 '\000', lastdamage = 0 '\000',
    track = {0, 0}, vision = "\000", fire = "\000", binding = 0 '\000', reach = "\000", extras = {0, 0}}, char_specials = {fight_veh = 0x0, fighting = 0x0, hunting = 0x0,
    programming = 0x0, conjure = {24647872, 0, 24647904, 0}, num_spirits = 24645856, idnum = 24650352, nervestrike = false, tempquiloss = 0, cost_breakup = 0, avail_offset = 0,
    shooting_dir = 0, position = 0 '\000', defined_position = 0x0, leave = 0x0, arrive = 0x0, target_mod = 0, carry_weight = 0, carry_items = 0 '\000', foci = 0, last_healed = 0,
    timer = 30798336, actions = 0, coord = {0, 0, 44805408}, subscribe = 0x0, rigging = 0x0, mindlink = 0x41, spirits = 0x4e54207078450205, saved = {powerpoints = 588,
      left_handed = 121, cur_lang = 27756, act = {static BITFIELD_SIZE = 4, static bits_per_var = 32, static total_width = 128, data = {1347962114, 1162433093, 38093646,
          1162893381}}, affected_by = {static BITFIELD_SIZE = 4, static bits_per_var = 32, static total_width = 128, data = {1313163602, 1298089283, 415809, 0}}, skills = {
        "\000", "\000", "\000", "\000", "!", "\000", "\000", "\000", "\220\t", "\255\002", "\000", "\000", "0\v", "[\002", "\000", "\000", "P\r", "[\002", "\000", "\000", "!",
        "\000", "\000", "\000", "\240\217", "\252\002", "\000", "\000", "0\r", "[\002", "\000", "\000", "p\r", "[\002", "\000", "\000", "!", "\000", "\000", "\000", "\340)",
        "\255\002", "\000", "\000", "P\r", "[\002", "\000", "\000", "\220\r", "[\002", "\000", "\000", "!", "\000", "\000", "\000", "\320\t", "[\002", "\000", "\000", "p\r",
        "[\002", "\000", "\000", "\020\017", "[\002", "\000", "\000", "a\001", "\000", "\000", "\000", "u\t", "\000" <repeats 39 times>, "\f", "\000", "\001@", "\000", "\000",
        "\000", "\000", "\000", "\000", "\000", "\002\210", "@", "\000", "\000", "\000", "\000", "\000", "\000", "\315", <incomplete sequence \314>, "L=", "\000", "\000", "\002",
        "\000"}, powers = {"\000", "\000", "\000", "\000", "\000", "\000", "\000", "\000", "\b ", " ", "\000" <repeats 30 times>, "\340W", "~\001", "\000"},
      metamagic = "\000\000p_~\001\000\000\000", centeringskill = 14272, boosted = {{382, 0}, {0, 11664}, {382, 0}}, masking = 0 '\000', points = 0, dirty = false}},
  player_specials = 0x0, mob_specials = {last_direction = 0 '\000', attack_type = 0, default_pos = 0 '\000', active = 0, memory = 0x2ad0e40, mob_skills = {0, 0, 0, 0, 0, 0, 0, 0,
      0, 0}, wait_state = 0, quest_id = 0, value_death_nuyen = 0, value_death_items = 0, value_death_karma = 2512, count_death = 603, alert = 0 '\000', alerttime = 0, spare1 = 0,
    spare2 = 33, lasthit = 39521712}, in_veh = 0x25b0d90, vfront = 144, persona = 0x161, squeue = 0xec5, sustained = 0x0, ssust = 0x0, equipment = {0x0, 0x600000000, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x10000000d, 0x0, 0x40800100000000, 0x0, 0x4120000000000000, 0x200008ca0, 0x0, 0x0, 0x60006060a, 0x40e00000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1868250,
    0x1868290, 0x1864830, 0x18679d0, 0x0, 0x0, 0x0, 0x0, 0x18682c0, 0x2ad0e40, 0x0, 0x0, 0x0, 0x0, 0x25b0db0, 0x0}, carrying = 0x0, desc = 0x21, cyberware = 0x25b0f30,
  bioware = 0x25b0f10, next_in_room = 0x2aa9260, next = 0x21, next_fighting = 0xf6340000, next_in_zone = 0x0, next_in_veh = 0x0, next_watching = 0x21, followers = 0xf6340000,
  master = 0x25b10f0, spells = 0x0, pgroup = 0x21, pgroup_invitations = 0x74656c64754d, congregation_bonus_pool = 0, alias_dirty_bit = false, bullet_pants = {{0, 0, 0, 0, 0, 33},
    {0, 0, 0, 0, 63028, 0}, {0, 4400, 603, 0, 0, 45008}, {683, 0, 0, 33, 0, 0}, {0, 11828, 12337, 12590, 0, 0}, {0, 0, 0, 44176, 61452, 32767}, {0, 33, 0, 0, 0, 0}, {63028, 0, 0,
      4464, 603, 0}, {0, 14799, 0, 0, 0, 33}, {0, 0, 0, 28245, 28267, 30575}, {110, 3232, 63028, 32767, 0, 0}, {0, 0, 0, 33, 0, 0}, {0, 0, 63028, 1, 0, 0}, {0, 0, 0, 3232, 63028,
      32767}, {0, 49, 0, 0, 0, 0}, {63028, 1, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0}, {0, 0, 0, 48, 0, 0}}}
```
The referenced code for the crash is:
```
if (temp->data->carried_by)
   affect_total(temp->data->carried_by);
```
Carried_by appears to be pointing to previously-freed data that was then consumed to load an object. Under what circumstances does the carried_by pointer not get cleared?

**Comment by AwakeMUD** [comment]
This is potentially resolved (issue was due to weird saving patterns in apartments). Will close until it reoccurs.
